CREATE TABLE [IntrigueCards] (
  [Id] INTEGER  NOT NULL
, [CardNo] bigint  NOT NULL
, [Type] text NOT NULL
, [Name] text NOT NULL
, [Era] text NOT NULL
, [DisplayText] text NOT NULL
, [DisplayImage] text NOT NULL
, CONSTRAINT [sqlite_master_PK_IntrigueCards] PRIMARY KEY ([Id])
);

INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (14,63,'Intrigue','Assassin','Early','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (15,64,'Intrigue','Blackmail','Early','<p>You may attempt one unopposed persuasion Attempt during your initiative against a non-Faction Leader Senator of your choice.</p> <p>If it fails, the target Senator''s Influence and Popularity are each reduced by DR. </p> Not playable vs Cicero or the Catos.','blackmail.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (16,65,'Intrigue','Influence Peddling','Early','<p>Backroom deals have caused a swing in loyalties to your Faction.</p> Use this card anytime other than during the Revolution Phase to draw an unplayed card at random from an opponent of your choice.','influence-peddling.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (17,66,'Intrigue','Secret Bodyguard','Early','<p>Use after an Assassination Attempt resolution to subtract 1 from the dr. </p> If the Assassin is not caught, one reroll is allowed for each Secret Bodyguard played to see if the Assassin is caught, even if Attempt is successful.','secret-bodyguard.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (18,67,'Intrigue','Seduction','Early','<p>Your Faction Leader seduces the wife of another Senator.</p> Use during your initiative to make an Unopposed Persuation Attempt vs the (non-Faction Leader) Senator of your choice.','seduction.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (19,68,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (20,69,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (21,70,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (22,71,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (23,72,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (24,73,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (25,74,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (26,75,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (27,76,'Intrigue','Tribune','Early','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (28,77,'Intrigue','Assassin','Middle','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (29,78,'Intrigue','Assassin','Middle','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (30,79,'Intrigue','Graft','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (31,80,'Intrigue','Influence Peddling','Middle','<p>Backroom deals have caused a swing in loyalties to your Faction.</p> Use this card anytime other than during the Revolution Phase to draw an unplayed card at random from an opponent of your choice.','influence-peddling.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (32,81,'Intrigue','Mob Incited To Violence','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (33,82,'Intrigue','Murder Of A Tribune','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (34,83,'Intrigue','Murder Of A Tribune','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (35,84,'Intrigue','Secret Bodyguard','Middle','<p>Use after an Assassination Attempt resolution to subtract 1 from the dr. </p> If the Assassin is not caught, one reroll is allowed for each Secret Bodyguard played to see if the Assassin is caught, even if Attempt is successful.','secret-bodyguard.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (36,85,'Intrigue','Secret Bodyguard','Middle','<p>Use after an Assassination Attempt resolution to subtract 1 from the dr. </p> If the Assassin is not caught, one reroll is allowed for each Secret Bodyguard played to see if the Assassin is caught, even if Attempt is successful.','secret-bodyguard.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (37,86,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (38,87,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (39,88,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (40,89,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (41,90,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (42,91,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (43,92,'Intrigue','Tribune','Middle','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (44,93,'Intrigue','Assassin','Late','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (45,94,'Intrigue','Assassin','Late','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (46,95,'Intrigue','Assassin','Late','<p>Support for your Assassination plot is widespread.</p> <p>Use when performing an Assassination Attempt to add 1 to your dr roll and any Bodyguard re-rolls.</p> Play before resolution.','assassin.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (47,96,'Intrigue','Cleopatra','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (48,97,'Intrigue','Graft','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (49,98,'Intrigue','Influence Pedding','Late','<p>Backroom deals have caused a swing in loyalties to your Faction.</p> Use this card anytime other than during the Revolution Phase to draw an unplayed card at random from an opponent of your choice.','influence-peddling.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (50,99,'Intrigue','Murder Of A Tribune','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (51,100,'Intrigue','Open Bodyguard','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (52,101,'Intrigue','Proscription','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (53,102,'Intrigue','Secret Bodyguard','Late','<p>Use after an Assassination Attempt resolution to subtract 1 from the dr. </p> If the Assassin is not caught, one reroll is allowed for each Secret Bodyguard played to see if the Assassin is caught, even if Attempt is successful.','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (54,103,'Intrigue','Tribune','Late','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (55,104,'Intrigue','Tribune','Late','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (56,105,'Intrigue','Tribune','Late','<p>Use to by-pass Presiding Magistrate and initiate proposal in the Senate. </p> <p>Use to cancel Prosecution or veto proposal in the Senate when voting. </p>May not veto last eligable candidate(s), Consul for Life, Assination Prosecutions or proposals of a Dictator.','tribune.png');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (57,106,'Intrigue','Acilian','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (58,107,'Intrigue','Calpurian Law','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (59,108,'Intrigue','Military Reforms','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (60,109,'Intrigue','Servilian Law','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (61,110,'Intrigue','Tradition Erodes','Middle','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (62,111,'Intrigue','Gabinian Law','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (63,112,'Intrigue','Julian Law','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (64,113,'Intrigue','Manilian Law','Late','Text','Image');
INSERT INTO [IntrigueCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[DisplayImage]) VALUES (65,114,'Intrigue','Plautian-Papirian Law','Late','Text','Image');
