CREATE TABLE [WarCards] (
  [Id] INTEGER  NOT NULL
, [CardNo] bigint  NOT NULL
, [Type] text NOT NULL
, [Name] text NOT NULL
, [Era] text NOT NULL
, [DisplayText] text NULL
, [WarName] text NOT NULL
, [DisplayImage] text NOT NULL
, [Legions] bigint  NOT NULL
, [FleetSupport] bigint  NOT NULL
, [Fleets] bigint  NOT NULL
, [Talents] bigint  NOT NULL
, [Disasters] text NULL
, [StandOffs] text NOT NULL
, [DefaultStatus] text NULL
, CONSTRAINT [sqlite_master_PK_WarCards] PRIMARY KEY ([Id])
);

INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (1,115,'War','1st Gallic War','Early','Victory creates Province of Cisalpine Gaul.','Gallic','gallic.png',10,0,0,20,'13','15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (2,116,'War','1st IllyrianWar','Early','<p>Drought prevails even if inactive until defeated.</p> Creates Province of Illyricum if both Illyrian Wars defeated.','Illyrian','illyrian.png',5,3,0,10,'5','17','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (3,117,'War','1st Macedonian War','Early','Revolt if Greece is a Province.','Macedonian','macedonian.png',12,10,0,25,'12','11,18','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (4,118,'War','1st Punic War','Early','Victory creates Provinces of Sciily and Sardinia-Corsica.','Punic','punic.png',10,5,10,35,'13','11,14','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (5,119,'War','2nd Illyrian War','Early','Creates Province of Illyricum if both Illyrian Wars defeated.','Illyrian','illyrian.png',4,2,0,10,'5','17','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (6,120,'War','2nd Macedonian War','Early','Revolt if Greece is a Province.','Macedonian','macedonian.png',10,5,0,45,'13','14','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (7,121,'War','2nd Punic War','Early','<p>Make dr roll to destroy Tax Farmer of that number until defeated.</p> Victory creates Provinces of Nearer and Further Spain.','Punic','punic.png',15,5,0,25,'10','11,15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (8,122,'War','Syrian War','Early','Revolt if Syria is a Province.','Syrian','syrian.png',6,2,0,45,'16','15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (9,123,'War','1st Cilician Pirates','Middle','<p>Creates or worsens Drought event.</p> Victory creates Province of Cilicia-Cyprus.','Cilician','cilician.png',3,2,8,10,'18','15','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (10,124,'War','1st Sicilian Slave Revolt','Middle','<p>Creates or worsens Drought event.</p> Destroys Sicilian Grain Concession. ','Sicilian','sicilian.png',7,1,0,0,'7','15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (11,125,'War','2nd Sicilian Slave Revolt','Middle','<p>Creates or worsens Drought event.</p> Destroys Sicilian Grain Concession.','Sicilian','sicilian.png',4,0,0,0,'17','15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (12,126,'War','3rd Macedonian War','Middle','Revolt if Greece is a Province.','Macedonian','macedonian.png',8,5,0,35,'8','14','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (13,127,'War','3rd Punic War','Middle','Victory creates Province of Africa.','Punic','punic.png',7,1,0,20,'7','15','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (14,128,'War','4th Macedonian War','Middle','Victory creates Province of Greece.','Macedonian','macedonian.png',5,1,0,30,'5','17','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (15,129,'War','Germanic Migrations','Middle','When attacked immediately create Province of Narbonese Gaul regardless of result.','Germanic','germanic.png',15,0,0,15,'10','11','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (16,130,'War','Jugurthine War','Middle',NULL,'Jugurthine','jugurthine.png',8,2,0,25,'14','13','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (17,131,'War','Numantine War','Middle','Inactive if Nearer Spain is not yet a Province.','Numantine','numantine.png',8,2,0,0,'14','11,18','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (18,132,'War','Spanish Revolts','Middle','Inactive if Further Spain is not yet a Province.','Spanish','spanish.png',6,2,0,0,'6','11,16','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (19,133,'War','1st Mithridatic War','Late','Revolt if Bithynia-Pontus is a Province.','Mithridatic','mithridatic.png',10,5,0,30,'13','14','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (20,134,'War','2nd Cilician Pirates','Late','Creates or worsens Drought event even if Inactive.','Cilician','cilician.png',3,2,6,10,'18','12','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (21,135,'War','2nd Gallic War','Late','<p>Revolt if Transalpine Gaul is a Province.</p> Victory creates Province of Transalpine Gaul.','Gallic','gallic.png',12,0,0,15,'12','16','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (22,136,'War','2nd Mithridatic War','Late','Revolt if Bithynia-Pontus is a Province.','Mithridatic','mithridatic.png',6,4,0,15,'16','17','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (23,137,'War','3rd Gallic War','Late','<p>Revolt if Transalpine Gail is a Province</p< Victory creates Province of Transalpine Gaul.','Gallic','gallic.png',15,0,0,15,'10','17','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (24,138,'War','3rd Mithridatic War','Late','Victory creates Provinces of Syria and Bithynia-Pontus.','Mithridatic','mithridatic.png',8,6,0,25,'14','11,17','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (25,139,'War','Alexandrine War','Late','<p>Creates or worsens Drought event.</p> Destroys Egyptian Grain Concession.','Alexandrine','alexandrine.png',2,2,10,25,'18','17','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (26,140,'War','Gladiator Slave Revolt','Late','Make dr roll to destroy Tax Farmer of that number until defeated.','Gladiator','gladiator.png',6,0,0,0,'6','16','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (27,141,'War','Invasiojn of Britain','Late','Inactive until Rome attacks.','Britain','britain.png',4,2,0,10,'5','17','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (28,142,'War','Invasion of Germany','Late','Inactive until Rome attacks.','Germany','germanic.png',6,0,0,10,'16','18','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (29,143,'War','Parthian War','Late',NULL,'Parthian','parthian.png',12,2,0,35,'12','18','Active');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (30,144,'War','Sertorian Revolt','Late','Inactive if Nearer / Further Spain are not Provinces.','Sertorian','sertorian.png',8,2,0,0,'14','13','Inactive');
INSERT INTO [WarCards] ([Id],[CardNo],[Type],[Name],[Era],[DisplayText],[WarName],[DisplayImage],[Legions],[FleetSupport],[Fleets],[Talents],[Disasters],[StandOffs],[DefaultStatus]) VALUES (31,145,'War','Social War','Late','Activates all Inactive Wars requiring a matching War, but does not double strength','Social','social.png',10,0,0,15,'13','16','Active');
